[tool.flake8]
max-line-length = 120
exclude = ["EEGModels.py"]

[tool.pylint.'MAIN']
ignore = ["EEGModels.py"]

[tool.pylint.'FORMAT']
max-line-length = 120

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
line-length = 120